// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"0","screenWidth":"1960","screenHeight":"1200","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"YEP_ExternalLinks","status":true,"description":"v1.01 Link back to your home page through the title screen\nand also be able to link your players from within the game.","parameters":{"Home Page URL":"http://www.bikapikabi.com/forum.php","Home Page Text":"千酥喵联盟","Popup Blocker Notice":"本游戏出至千酥喵联盟！ "}},
{"name":"WindowResize","status":true,"description":"ゲーム起動時のウィンドウサイズを変更します。","parameters":{"width":"1960","height":"1200"}},
{"name":"DP_MapZoom","status":true,"description":"マップの拡大率を制御します。","parameters":{"Base Scale":"2","Encount Effect":"true","Camera Controll":"true","Weather Patch":"true","Picture Size Fixation":"true","Old Focus":"false"}},
{"name":"SimpleSingleActorMenu","status":true,"description":"シンプルなメニュー画面を提供するプラグインです。\r\n恐らく簡易的なシングルアクタープラグインとして動作すると思われます。","parameters":{}},
{"name":"FTKR_AlternatingTurnBattle","status":true,"description":"v2.1.0 敵味方交互にターンが進むターン制戦闘システム","parameters":{"TurnEnd Command":"ターン終了","Change Player":"-1","Call Party Command":"-1","Start Actor Command":"true","Enable Auto Player Turn End":"true","Enabled Auto Select TurnEnd Command":"true","Confused Action Timing":"1","--- 行動回数 ---":"","Disable AC":"false","--- 行動済みのアクター ---":"","Activated Sv Actor Sign":"0","Not Activated Sv Actor Sign":"0","Cannot Select Activated Actor":"ture"}},
{"name":"CharacterPopupDamage","status":true,"description":"","parameters":{}},
{"name":"Mano_InfoWindow","status":true,"description":"情報ウィンドウを出します","parameters":{"list":"[\"{\\\"text\\\":\\\"HP\\\",\\\"textColor\\\":\\\"0\\\",\\\"valueId\\\":\\\"3\\\",\\\"paddingX\\\":\\\"0\\\"}\",\"{\\\"text\\\":\\\"ATK\\\",\\\"textColor\\\":\\\"0\\\",\\\"valueId\\\":\\\"1\\\",\\\"paddingX\\\":\\\"0\\\"}\",\"{\\\"text\\\":\\\"DEF\\\",\\\"textColor\\\":\\\"0\\\",\\\"valueId\\\":\\\"2\\\",\\\"paddingX\\\":\\\"0\\\"}\",\"{\\\"text\\\":\\\"铜钥匙\\\",\\\"textColor\\\":\\\"0\\\",\\\"valueId\\\":\\\"17\\\",\\\"paddingX\\\":\\\"0\\\"}\",\"{\\\"text\\\":\\\"银钥匙\\\",\\\"textColor\\\":\\\"0\\\",\\\"valueId\\\":\\\"18\\\",\\\"paddingX\\\":\\\"0\\\"}\",\"{\\\"text\\\":\\\"紫钥匙\\\",\\\"textColor\\\":\\\"0\\\",\\\"valueId\\\":\\\"19\\\",\\\"paddingX\\\":\\\"0\\\"}\",\"{\\\"text\\\":\\\"金钱\\\",\\\"textColor\\\":\\\"0\\\",\\\"valueId\\\":\\\"20\\\",\\\"paddingX\\\":\\\"0\\\"}\"]","enableSwitch":"300","windowX":"0","windowY":"0","windowWidth":"250"}},
{"name":"PictureVariableSetting","status":true,"description":"ピクチャ関連のイベント機能拡張プラグイン","parameters":{"初期値":"OFF","ピクチャ表示最大数":"400"}},
{"name":"TitleSceneExtensions","status":false,"description":"タイトル画面を変更します。","parameters":{"選択肢の画像":"","回転タイプ":"1","回転の中心X座標":"320","回転の中心Y座標":"300","回転する量":"120","初期位置の補正":"90","オフセット":"120"}}
];
